### ISSUE TITLE
When password is automatically set by CC still shows admin/secret defaults on output

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/vagrant#130]
I noticed that the welcome message is giving the user the idea that admin / secret must still be used when CC sets the password. 

```
    default: SUCCESS: Your peer is up. Welcome to the Horde!
    default: -----------------------------------------------
    default:
    default: Next steps ...
    default: Make sure Subutai's E2E Extension/Plugin is installed in your browser
    default: Search for 'Subutai' in your browser's extension/plugin store to find it and install.
    default: SUBUTAI_BRIDGE_IFACE = eth0
    default:     Console URL: https://172.17.174.219:8443
    default:
    default: Default u/p: 'admin' / 'secret'
    default: Vagrant ssh into box and change the 'subutai'/'ubuntai' user password!
    default: If you forget the url above, just take a look in .vagrant/generated.yml
```

>     default: Default u/p: 'admin' / 'secret'
>     default: Vagrant ssh into box and change the 'subutai'/'ubuntai' user password!

If CC is driving the creation and the password is set, or if the password is set in the YAML configuration then we need a different message. Also this **ubuntai** (which is old and no longer the password anymore right) has to be updated! 

If the password is already set somehow we should replace these two lines to read like so:

>    default: Use the 'admin' user password set for this peer (in CC|yaml config)
>    default: You can use the 'root' user password provided (in CC|yaml config)
